apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-test-container
  name: kube-test-container
  namespace: namespace-b
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kube-test-container
  template:
    metadata:
      labels:
        app: kube-test-container
    spec:
      containers:
      - name: kube-test-container
        image: gcr.io/google-samples/hello-app:1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 10Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kube-test-container
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube-test-container
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: namespace-b
spec:
  ingressClassName: nginx
  rules:
    - host: hello.zach
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-test-container
                port:
                  number: 80