apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validator
  namespace: default
webhooks:
  - name: validator.default.svc
    clientConfig:
      service:
        name: validator
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBekNDQXVzQ0ZBT00xQTF5RlRpZ2VoSytHVzdlL0ErR1BoVy9NQTBHQ1NxR1NJYjNEUUVCRFFVQU1JRzkKTVFzd0NRWURWUVFHRXdKRVJURVFNQTRHQTFVRUNBd0hRMjlzYjJkdVpURVFNQTRHQTFVRUJ3d0hRMjlzYjJkdQpaVEVQTUEwR0ExVUVFUXdHTkRJME1qUXlNUlF3RWdZRFZRUUpEQXRJWVd4c2J5QWdNVFl5TVRFVE1CRUdBMVVFCkNnd0taMmxoYm5SemQyRnliVEVaTUJjR0ExVUVDd3dRUlcxdmFua2dSR1Z3WVhKMGJXVnVkREVSTUE4R0ExVUUKQXd3SWVtRmphQzVqYjIweElEQWVCZ2txaGtpRzl3MEJDUUVXRVc1dkxYSmxjR3g1UUhwaFkyZ3VZMjl0TUI0WApEVEl6TURZeU1qQXpNRFkxT1ZvWERUSXpNRGN5TWpBek1EWTFPVm93Z2IweEN6QUpCZ05WQkFZVEFrUkZNUkF3CkRnWURWUVFJREFkRGIyeHZaMjVsTVJBd0RnWURWUVFIREFkRGIyeHZaMjVsTVE4d0RRWURWUVFSREFZME1qUXkKTkRJeEZEQVNCZ05WQkFrTUMwaGhiR3h2SUNBeE5qSXhNUk13RVFZRFZRUUtEQXBuYVdGdWRITjNZWEp0TVJrdwpGd1lEVlFRTERCQkZiVzlxZVNCRVpYQmhjblJ0Wlc1ME1SRXdEd1lEVlFRRERBaDZZV05vTG1OdmJURWdNQjRHCkNTcUdTSWIzRFFFSkFSWVJibTh0Y21Wd2JIbEFlbUZqYUM1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRQ2hkNjlGSWJaNHFldjNGUWZ0RUZPc3V0RDRMZlBLVGVmd0x1aDVYSWFNUFhhaQpyMHNiMWJIdyttNVl3c21aeEM5T0Q4QUkwZERMbVBhNyt2OXdBaEZJbXVHR1FLbTFUeVNHTVZOY0t4K0dlUWJiCkFWaWlneThQb2Q1eVY5cStkOHQybzd3Z3hsdlVnZ08wN0lpdTIyOHI3UTFaaTg1TWt2VW9NUE82L2tHUXQ5TEgKczlhUUtwT3ZrOVpWVUFMZUJ1dURnYlh0WVM3QUFRZFU5THZvazEvd1kwM1lUeTlybjllNW9ENE5SaU9XYzduRwpBTFNnV0xWcDlFdlphejN3MytCeC8ycmF5bHhwRCtISDFDZzNodUszUk5vNjhKZm9qWEpNbnpGbHY4TU1XUWswCjE1Q1psUVBrOEpJQUpWcEFreGNCVEN2eTZRQzM3Zk9UdXZaZEpUZVpBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRU4KQlFBRGdnRUJBQ0NhTFBib0tMOCtGQWd6NWhBZlJBL01MVWdNNkZIelNlWW92Nk9RZ1RHdkFINUlscXNCM0Vvawpmb2pUSVUrUWdyZDZIYjA4Z2xuNlJHd0VSOWQ0R21ISnhzd1ZRMVlIWDNHOVRZeUtmaHMrUlFXbDBjUU5qRVNYCmx3TDE1S3NYUElWZmJIdWhQbVd2b0tCSnhXaTlzR1JmZXB6aUFhQlZySy9ibDJ0L1hxY1Y0NHk2bHNwMll6L0sKWEJFVTduekxwU29sQzU2d2JaWWhuR0FlUmFZS2hUc1UyTzhYMDRzNXJzS2Z1Sk9DbnNuVXkwcTJNU2hOYlphRQpjcWcxLzMzOW52ZjRVNTZhU0hnRUN3eGFUYTBEeFVzVDFSTisxTFJ4dCtyeUhTcm5rRzFuRWREdjBwaVViZGhOCnJZTUxSRElxVmRXK0lPd3h5OHZ2blkyRnp1V0FCRzg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        resources: ["*"]
    failurePolicy: Ignore
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5